// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Reference adapter for checking proof rails in an app, router, hook, or issuer portal.
/// @dev This is not a verifier implementation. Wire each rail to the verifier generated by your proof system.
contract ProofRailsVerifier {
    enum Rail {
        AgentRisk,
        TradingEligibility,
        ExecutionHook,
        PortfolioExposure,
        DividendEntitlement,
        IssuerBacking
    }

    struct ProofRail {
        Rail rail;
        bytes32 policyCommitment;
        bytes32 intentHash;
        bytes32 nullifier;
        bytes proof;
    }

    mapping(bytes32 => bool) public usedNullifiers;
    mapping(Rail => address) public verifierForRail;

    event RailVerifierSet(Rail indexed rail, address indexed verifier);
    event RailChecked(Rail indexed rail, bytes32 indexed intentHash, bytes32 indexed nullifier);

    function setRailVerifier(Rail rail, address verifier) external {
        verifierForRail[rail] = verifier;
        emit RailVerifierSet(rail, verifier);
    }

    function checkRail(ProofRail calldata rail) public returns (bool) {
        require(verifierForRail[rail.rail] != address(0), "RAIL_VERIFIER_MISSING");
        require(rail.intentHash != bytes32(0), "INTENT_REQUIRED");

        if (rail.nullifier != bytes32(0)) {
            require(!usedNullifiers[rail.nullifier], "NULLIFIER_USED");
            usedNullifiers[rail.nullifier] = true;
        }

        require(_verify(rail), "RAIL_PROOF_INVALID");
        emit RailChecked(rail.rail, rail.intentHash, rail.nullifier);
        return true;
    }

    function checkRails(ProofRail[] calldata rails) external returns (bool) {
        for (uint256 index = 0; index < rails.length; index += 1) {
            checkRail(rails[index]);
        }
        return true;
    }

    function _verify(ProofRail calldata rail) internal view returns (bool) {
        // Replace this placeholder with a call into the generated verifier for rail.rail.
        // Public inputs should include policyCommitment, intentHash, and any rail-specific nullifier.
        return rail.proof.length > 0 && verifierForRail[rail.rail] != address(0);
    }
}
